template: minimal
default_language: fr
menu:
    - index:
        text: Home
        attributes:
            class: menu-item
    - about:
        text: About
        attributes:
            class: menu-item
    - contact:
        text: Contact
        attributes:
            class: menu-item
