# A template must be specified
template: template-bedrock
site_title: Bedrock Template
default_language: en
languages:
    - en
    - fr
blog: ubiwebblog
blog_base: /blog

gallery_base: /gallery
gallery_path: /images/gallery
menu_active_class: active

menu:
    main:
        home:
            text: Home <span class="caret"></span>
            anchor:
                class: nav-link dropdown-toggle
                id: navbarDropdown
                role: button
                data-toggle: dropdown
                aria-haspopup: true
                aria-expanded: false
            attributes:
                class: nav-item dropdown
            submenu:
                "http://ubiweb.ca":
                    text: Ubiweb
                    anchor:
                      class: dropdown-item
        about:
            text: About
            attributes:
              class: nav-item
            anchor:
              class: nav-link
        # styleguide:
        #     text: Styleguide
        #     attributes:
        #       class: nav-item
        #     anchor:
        #       class: nav-link
        blog:
            text: Blog
            attributes:
              class: nav-item
            anchor:
              class: nav-link
        gallery:
            text: Gallery
            attributes:
              class: nav-item
            anchor:
              class: nav-link
        contact:
            text: Contact
            attributes:
              class: nav-item
            anchor:
              class: nav-link
    onepager:
        # "#about":
        about:
            text: About
            attributes:
              class: nav-item
            anchor:
              class: nav-link
              # data-scroll-to: about
              # data-scroll-to-offset: header
        blog:
            text: Blog
            attributes:
              class: nav-item
            anchor:
              class: nav-link
        gallery:
            text: Gallery
            attributes:
              class: nav-item
            anchor:
              class: nav-link
        # "#contact":
        contact:
            text: Contact
            attributes:
              class: nav-item
            anchor:
              class: nav-link
              # data-scroll-to: contact
        # styleguide:
        #     text: Styleguide
        #     attributes:
        #       class: nav-item
        #     anchor:
        #       class: nav-link

social:
    facebook: https://www.facebook.com/ubiweb1/
    twitter: https://twitter.com/ubiweb
    linkedin: https://ca.linkedin.com/company/ubiweb
    youtube: https://www.youtube.com/user/ubiweb
    google: https://plus.google.com/107381435430037598028

business:
    type: ProfessionalService
    name: Ubiweb
    tagline: Specialized in creating and getting your business noticed.
    url: https://ubiweb.ca
    logo: /logo.png
    image: /ubiweb.jpg
    description: Your local business' online partner.
    address: 644 Courcelle St \#405|Montreal|QC|H4C 3C5
    latitude: 45.4743734
    longitude: -73.5947416
    map: https://www.google.ca/maps/place/UbiWeb/@45.4743734,-73.5947416,17z/data=!4m12!1m6!3m5!1s0x4cc91098e0800695:0x4b422acd4324464d!2sUbiWeb!8m2!3d45.4743734!4d-73.5925529!3m4!1s0x4cc91098e0800695:0x4b422acd4324464d!8m2!3d45.4743734!4d-73.5925529
    hours:
      Monday: 00:00-23:59
      Tuesday: 00:00-23:59
      Wednesday: 00:00-23:59
      Thursday: 00:00-23:59
      Friday: 00:00-23:59
      Saturday: 00:00-23:59
      Sunday: 00:00-23:59
    phone: +1(514) 788-4456
    price: $
    payment_types: mastercard|visa|american express|interact|cash
    age: 5
    email: info@ubiweb.ca
    license: RBQ 5680-0535-01
